---
name: ARDUINO_CI

on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          cli-version: "latest"
          fqbn: "arduino:avr:uno"
          libraries: "- source-path: ./"
          sketch-paths: "- ./examples"
          verbose: true
